= Connecting to Astra - Python
:page-layout: gcx-full
:driver-matrix-url: https://docs.datastax.com/en/driver-matrix/doc/driver-matrix.html
:secure-connect-bundle-url: https://docs.datastax.com/en/astra-serverless/docs/connect/secure-connect-bundle.html

Using a Cassandra driver to connect to a https://astra.datastax.com[DataStax Astra] database is almost identical to using the driver to connect to any Apache Cassandra® database. The only differences are:

* how the driver is configured in an application
* the need to obtain a secure connect bundle

== Driver configuration

All DataStax drivers have configuration file attributes, builder methods, or constructor parameters for pointing to the secure connect bundle. The database username and password are specified through the normal driver APIs for configuring a plain text authentication provider, or through using one of the convenience methods for username and password.

When using the secure connect bundle, the DataStax drivers automatically establish mutually authenticated TLS connections to the service. You do not have to unzip the secure connect bundle or supply contact points.

After establishing a connection the resulting session is optimally configured for interacting with your Astra database. It is possible (but not required) to use other advanced features, such as Speculative query execution and Execution profiles.

The {driver-matrix-url}[DataStax driver] documentation for your language contains getting started examples and API documentation. Upgrade to the latest minor version of your language’s driver to get the new Astra connection API.

== Prerequisites

* Create an Astra database and {secure-connect-bundle-url}[download your secure connect bundle] that contains connection information such as contact points and certificates.

[.gcx-hook-connect='4-5']
== Import the required classes

Import the classes required to work with a cluster and cluster authentication.

[.gcx-hook-connect='8-11']
== Identify the required connection filenames in variables

Information specific to your Astra database is defined as variables to call in the connection class. 

[.gcx-hook-connect='16-23']
== Connecting to the database

Using a combination of the secure bundle file and its associated credentials, connect to your Astra database.

[.gcx-hook-connect='19-19']
== Specifying `use_default_tempdir`

The secure connect bundle needs to be extracted to load the certificates into the SSLContext. By default, the zip location is used as the base dir for the extraction. In some environments, the zip location file system is read-only (e.g Azure Function). With `use_default_tempdir` set to `True`, the default temporary directory of the system will be used as base dir.

[.gcx-hook-connect='24-25']
== Retrieving metadata

After connecting to the database, get a metadata object and retrieve information about the nodes that make up the cluster.

[.gcx-hook-connect='27-28']
== Create connection in main

Create a new connection client and connect.

== Astra differences from Apache Cassandra or DSE

In most circumstances, the client code for interacting with an Astra cluster will be the same as interacting with any other Cassandra cluster. The exceptions being:

* A cloud configuration must be passed to a Cluster instance via the cloud attribute (as demonstrated in the code example).

* An SSL connection will be established automatically. Manual SSL configuration is not allowed, and using `ssl_context` or `ssl_options` will result in an exception.

* A cluster's contact_points attribute should not be used. The cloud config contains all of the necessary contact information.

* If a consistency level is not specified for an execution profile or query, then `ConsistencyLevel.LOCAL_QUORUM` will be used as the default.

[.gcx-code-connect] 
[source,Python]
----
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from cassandra.auth import PlainTextAuthProvider
from cassandra.cluster import Cluster

class ConnectionClient:
    SECURE_CONNECT_BUNDLE = "/path/to/secure-connect-driver-demo.zip"
    CLIENT_ID = "client-id"
    CLIENT_SECRET = "client-secret"
    KEYSPACE = "demo"

    def __init__(self):
        self.session = None
    
    def connect(self):
        cloud_config = {
            "secure_connect_bundle" : self.SECURE_CONNECT_BUNDLE
            'use_default_tempdir': True
        }
        authProvider = PlainTextAuthProvider(self.CLIENT_ID, self.CLIENT_SECRET)
        cluster = Cluster(cloud = cloud_config, auth_provider = authProvider)
        self.session = cluster.connect(self.KEYSPACE)
        for host in cluster.metadata.all_hosts():
            print(f"{host}")

def main():
    client = ConnectionClient()
    client.connect()

if __name__ == "__main__":
    main()
----