= Executing bound statements
:page-layout: gcx-full
:secure-connect-bundle-url: https://docs.datastax.com/en/astra-serverless/docs/connect/secure-connect-bundle.html
:java-project-url: https://docs.datastax.com/en/developer/java-driver/4.14/manual/core/integration/#minimal-project-structure

Prepare a query string once, reuse with different values. More efficient than simple statements for queries that are used often.

== Prerequisites

* https://maven.apache.org/download.cgi[Download] and https://maven.apache.org/install.html[install] Maven.
* Create an Astra database and {secure-connect-bundle-url}[download your secure connect bundle] that contains connection information such as contact points and certificates.
* Create a minimal project structure as explained {java-project-url}[here]. 
* Create a xref:connecting-to-astra-java.adoc[connection to Astra].

== Procedure

[.gcx-hook-connect='7-8']
== Import classes for bound (prepared) statements

Import the classes that will allow bound and prepared statements to be executed.

[.gcx-hook-connect='10-20']
== Create a bound (prepared) statement

Create some bound and prepared statements.

[.gcx-hook-connect='49-80']
== Bind data to variables

Bind data to variables in statements for song data.

[.gcx-hook-connect='81-81']
== Execute bound statement

Execute bound statement on session object for song data.

[.gcx-hook-connect='82-104']
== Bind data to variables

Bind data to variables in statements for playlist data.

[.gcx-hook-connect='105-105']
== Execute bound statement

Execute bound statement on session object for playlist data.

[.gcx-hook-connect='108-112']
== Modify the main code

Modify the main code to execute all the code in the new classes.

[.gcx-code-connect] 
[source,Java] 
----
package biz.bisso.cstar;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import com.datastax.oss.driver.api.core.cql.BoundStatement;
import com.datastax.oss.driver.api.core.cql.PreparedStatement;

public class BoundStatementsClient extends StatementsClient {
    private static final String INSERT_SONGS_DATA_PREPARED = 
        "INSERT INTO demo.songs (id, title, album, artist, tags) VALUES (?, ?, ?, ?, ?);";
    private static final String INSERT_PLAYLISTS_DATA_PREPARED = 
        "INSERT INTO demo.playlists (id, song_id, title, album, artist) VALUES (?, ?, ?, ?, ?);";
    
    private PreparedStatement insertSongsDataStatement;
    private PreparedStatement insertPlaylistsDataStatement;
    
 	public BoundStatementsClient() {
 	}
    
	@Override
	public void createSchema() {
		session.execute(
				"DROP TABLE IF EXISTS demo.songs");
		session.execute(
				"DROP TABLE IF EXISTS demo.playlists");
		session.execute(
				"CREATE TABLE demo.songs (" +
					"id uuid PRIMARY KEY," + 
					"title text," + 
					"album text," + 
					"artist text," + 
					"tags set<text>," + 
					"data blob" + 
					");");
		session.execute(
				"CREATE TABLE demo.playlists (" +
					"id uuid," +
					"title text," +
					"album text, " + 
					"artist text," +
					"song_id uuid," +
					"PRIMARY KEY (id, title, album, artist)" +
					");");
		System.out.println("demo schema created.");
	}
	
	@Override
	public void loadData() {
		// songs table
 	    insertSongsDataStatement = session.prepare(INSERT_SONGS_DATA_PREPARED);
		Set<String> tags = new HashSet<String>();
		tags.add("jazz");
		tags.add("2013");
		BoundStatement boundStatement = insertSongsDataStatement.bind(
				UUID.fromString("756716f7-2e54-4715-9f00-91dcbea6cf50"),
				"La Petite Tonkinoise'",
				"Bye Bye Blackbird'",
				"Joséphine Baker",
				tags);
		session.execute(boundStatement);
		tags = new HashSet<String>();
		tags.add("1996");
		tags.add("birds");
		boundStatement = insertSongsDataStatement.bind(
				UUID.fromString("f6071e72-48ec-4fcb-bf3e-379c8a696488"),
				"Die Mösch",
				"In Gold'", 
				"Willi Ostermann",
				tags);
		session.execute(boundStatement);
		tags = new HashSet<String>();
		tags.add("1970");
		tags.add("soundtrack");
		boundStatement = insertSongsDataStatement.bind(
				UUID.fromString("fbdf82ed-0063-4796-9c7c-a3d4f47b4b25"),
				"Memo From Turner",
				"Performance",
				"Mick Jager",
				tags);
		session.execute(boundStatement);
		// playlists table
 	    insertPlaylistsDataStatement = session.prepare(INSERT_PLAYLISTS_DATA_PREPARED);
		boundStatement = insertPlaylistsDataStatement.bind(
				UUID.fromString("2cc9ccb7-6221-4ccb-8387-f22b6a1b354d"),
				UUID.fromString("756716f7-2e54-4715-9f00-91dcbea6cf50"),
				"La Petite Tonkinoise",
				"Bye Bye Blackbird",
				"Joséphine Baker");
		session.execute(boundStatement);
		boundStatement = insertPlaylistsDataStatement.bind(
				UUID.fromString("2cc9ccb7-6221-4ccb-8387-f22b6a1b354d"),
				UUID.fromString("f6071e72-48ec-4fcb-bf3e-379c8a696488"),
				"Die Mösch",
				"In Gold",
				"Willi Ostermann");
		session.execute(boundStatement);
		boundStatement = insertPlaylistsDataStatement.bind(
				UUID.fromString("3fd2bedf-a8c8-455a-a462-0cd3a4353c54"),
				UUID.fromString("fbdf82ed-0063-4796-9c7c-a3d4f47b4b25"),
				"Memo From Turner",
				"Performance",
				"Mick Jager");
		session.execute(boundStatement);
	}

	public static void main(String[] args) {
		BoundStatementsClient client = new BoundStatementsClient();
		client.connect();
		client.createSchema();
		client.loadData();
		client.close();
	}

}
----
